spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/UserServiceDB
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5001

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"

keycloak:
  base-url: http://keycloak:8080
  realm: master
  admin-api: ${keycloak.base-url}/admin/realms/${keycloak.realm}/users
  token-url: ${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/token
  client-id: salon-booking-client
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  grant-type: password
  scope: openid email profile
  username: ${KEYCLOAK_ADMIN_USERNAME}
  password: ${KEYCLOAK_ADMIN_PASSWORD}
  client-db-id: ${KEYCLOAK_DB_ID}