server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmysalon?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "@anuram1008"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: false

security:
  jwt:
    secret: "c3VjdXJlLWJvb2tteXNhbG9uLWp3dC1zZWNyZXQtYmFzZTY0LQ=="
    access-token-expiration-ms: 7200000
    refresh-token-expiration-ms: 604800000

stripe:
  api:
    key: "sk_test_change_me"

app:
  otp:
    dev-mode: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
